### ISSUE TITLE
 Can be added directly to the function body?

### ISSUE THREAD

**Issue by tiansin** [stef-k/laravel-goto-controller#1]
Can you add direct positioning to the body of the function? 
This is easier to use.

**Comment by stef-k** [comment]
Hi, I checked this in documentation and I could not find anything relevant. Right now I do not have time for a solution.

You are welcomed to submit a pull request if you have a working solution.

Thanks.

**Comment by stef-k** [comment]
fixed with b7030046f7d2dbded7ef23beaa91a4c859c40c74

thanks to @Smankusors
