### ISSUE TITLE
Make extension setting to not underline definitions

### ISSUE THREAD

**Issue by agm1984** [stef-k/laravel-goto-controller#10]
Nice work on the extension. It's 100% rad.

As shown in this image here, when I install this extension, it underlines all the controller definitions in `web.php`:
![image](https://user-images.githubusercontent.com/17655219/68367028-8bbcaf00-00e9-11ea-8184-d42fab28469a.png)

So I would like to request an extension **setting** that disables this. It would be nice to have a setting here to enable/disable it:

![image](https://user-images.githubusercontent.com/17655219/68366939-544e0280-00e9-11ea-9646-5825a3015f17.png)

And as a bonus, it would be nice if F12 would also goto the definition. I have other extensions that open files when I press F12, so it would be nice if this extension could do it also. The example extension I could cite is called `Vue Peek`.

**Comment by stef-k** [comment]
Opened 2 separate issues, please follow: #11 & #12
