### ISSUE TITLE
v0.0.9  Cannot find module 'n-readlines' 

### ISSUE THREAD

**Issue by nick322** [stef-k/laravel-goto-controller#16]
I updated vscode and this plugin.
Plugin not working and vscode Developer tools show ```Cannot find module 'n-readlines'```
![截圖 2020-10-05 15 40 52](https://user-images.githubusercontent.com/9151347/95052228-291cca80-0721-11eb-8f1d-ab7c5934e2a3.png)

Change to v0.0.7 is worked.

**Comment by stef-k** [comment]
`vsce` does not post install the dependencies from `package.json` file. 

Working on it

**Comment by stef-k** [comment]
it turn that it is a `yarn`  issue from `vsce` https://github.com/microsoft/vscode-vsce/issues/497

new version is coming 

@nick322  please check the v0.0.11

**Comment by nick322** [comment]
Still the same
![截圖 2020-10-05 16 56 27](https://user-images.githubusercontent.com/9151347/95059888-1956b380-072c-11eb-820c-8168ab577139.png)

**Comment by stef-k** [comment]
v0.0.12 is out, build by an older version of `vsce` just tested on linux and works as expected.

Please try to update the extension again.

**Comment by nick322** [comment]
@stef-k : v0.0.12 It's OK. Thanks!
