### ISSUE TITLE
Laravel 8 Compability

### ISSUE THREAD

**Issue by s-damian** [stef-k/laravel-goto-controller#17]
Hello, et thank for your gook package.

On some projects, I migrated to Laravel 8 with the new conventions:

` Route::post('add', [CustomerController::class, 'store']);`

Please, is it possible to have an compability ?

Thank youn.

**Comment by stef-k** [comment]
Yes, v0.0.12 (current) supports Laravel 8. If you haven't updated, please update to the newest version.

**Comment by Shujee** [comment]
@stef-k I have installed 0.0.12, but it still doesn't understand Laravel 8 syntax. No "hot link" appears when I move the mouse over the function name (`store` in the above example). This happens with and without ALT key pressed.

UPDATE
------
Looks like it works fine in web.php, but not in api.php.

**Comment by stef-k** [comment]
@Shujee  if it works on `web.php` then it should be working fine on `api.php` routes too.

The file containing route definitions does not play any role in the logic of the extension.

Maybe it is something else?
