### ISSUE TITLE
[FEAT] : Publish the extension to the Open VSX Registry

### ISSUE THREAD

**Issue by mhkb** [stef-k/laravel-goto-controller#24]
Would you be able to publish this extension to the Open VSX Registry (https://open-vsx.org/) so it's available to VS Code Compatible Editors, such as VSCodium?

**Comment by mhkb** [comment]
@stef-k there's a good guide for it here https://github.com/eclipse/openvsx/wiki/Publishing-Extensions but I'm happy to help if I can.

**Comment by stef-k** [comment]
Unfortunately, I do not have free time to publish it.

You are welcome to publish the extension on Open VSX registry. 

From what I read the process is almost the same, i.e

1. Create an account
2. Install the toolchain
3. Pull the code
4. Build and publish (using the isntalled toolchain)

**Comment by mhkb** [comment]
I've just tried, but unfortunately, I don't have the access rights:

``` 
DONE  Packaged: /var/folders/32/czw3lr692cv2m2gq7qt55jwr0000gn/T/tmp-52759v39CMGaeQv70.vsix (27 files, 851.62KB)

❌  Insufficient access rights for publisher: stef-k
```

I think I'd either need to fork it and publish it under my namespace (which I'd rather not do) or you'd need to add me as a namespace member to your stef-k namespace on the open vsx registry.

**Comment by stef-k** [comment]
@mhkb I've also tried to but it keeps saying that I don't have access rights to the newly created namespace. Opened an issue to claim the namespace. 

Once done and hopefully resolved, I'll add you as contributor to the namespace.

**Comment by stef-k** [comment]
The extension is up on Open VSX registry.

@mhkb you are a contributor.
