### ISSUE TITLE
On api.php no work

### ISSUE THREAD

**Issue by Snake231088** [stef-k/laravel-goto-controller#3]
On api.php no work

**Comment by stef-k** [comment]
Thanks for reporting this. Currently I have not free time to provide a fix.

**Comment by Shujee** [comment]
Did you ever get a chance to fix this? It appears to work with relative paths but not absolute ones.

![image](https://user-images.githubusercontent.com/5603658/55666662-602fc880-586b-11e9-9efd-a7c2066ee6b3.png)

**Comment by stef-k** [comment]
Unfortunately I don't have the time to fix any issue. 
I can however merge incoming fixes - new features.

**Comment by stef-k** [comment]
Actually this is fixed.  Tested today in a project of mine.
