### ISSUE TITLE
Add support to all files under /routes

### ISSUE THREAD

**Issue by vorban** [stef-k/laravel-goto-controller#9]
Currently, this only supports ./routes/web.php.
I'd love to have support for other files, (ex: ./routes/admin.php, ./routes/api.php).

Great work btw :)

**Comment by stef-k** [comment]
Will try to find some time to implement this.

**Comment by stef-k** [comment]
@KhroyaenSkrafhar I've found some time to check this issue against a project of mine. 

The project contains routes from `web.php` and `api.php` and both work as expected as shown bellow.

![image](https://user-images.githubusercontent.com/5731388/66706167-3da9cb00-ed38-11e9-8a1e-d4402fa3da74.png)

Closing this; Please open a new issue if you still have problems.
